# Generated by Django 2.2.24 on 2021-11-11 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211109_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
